### ISSUE TITLE
Rooster Logo

### ISSUE THREAD

**Issue by rbdr** [pablasso/twitiriqui#1]
First of all, THANK YOU for this project, it's my #1 favorite twitter client and I want to thank for the work you put in the open source community.

However, the old version (Twitiriqui legacy, the one on google code) had a rooster on the logo. This was my #1 use case. I don't understand why it was removed? But I don't want to go back to using tweetbot.

**Comment by pablasso** [comment]
I don't care

**Comment by salvadorbfm** [comment]
Please add a logo,  sometimes I think I'm using malware software because I don't see a logo.
